/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package cmx.examples

import jp.crestmuse.cmx.processing.CMXController
import jp.crestmuse.cmx.sound.SMFPlayer

class App {
    String getGreeting() {
        return 'Hello World!'
    }

    static void main(String[] args) {
        def app = new App()
        println app.greeting
        app.playMusic()
    }

    def playMusic() {
        CMXController cmx = CMXController.getInstance()
        println getClass().getResource('/KIRAKIRA.mid')
        cmx.smfread(getClass().getResource('/KIRAKIRA.mid').getPath())
        cmx.playMusic()
    }

}
